import {
  BadgeIndianRupee,
  BriefcaseBusiness,
  CalendarCheck,
  CalendarDays,
  CheckSquare,
  CircleHelp,
  FileCheck2,
  FileText,
  Fingerprint,
  GitFork,
  HeartPulse,
  IdCard,
  Landmark,
  Layers3,
  LayoutDashboard,
  Link2,
  Megaphone,
  MessageSquareText,
  ReceiptText,
  Settings,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Trophy,
  Users,
} from "lucide-react";
import type { Route } from "next";
import type { LucideIcon } from "lucide-react";

export const nav: Array<{ href: Route; label: string; icon: LucideIcon; group?: string }> = [
  { href: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/setup", label: "Setup Wizard", icon: Sparkles },
  { href: "/analytics", label: "Analytics", icon: TrendingUp },
  { href: "/saas", label: "SaaS Billing", icon: Layers3 },
  { href: "/saas-admin" as any, label: "SaaS Admin", icon: ShieldCheck },
  { href: "/approvals", label: "Approvals", icon: CheckSquare },
  { href: "/assets", label: "Assets", icon: BriefcaseBusiness },
  { href: "/performance", label: "PMS", icon: Target },
  { href: "/employees", label: "Directory", icon: Users },
  { href: "/documents", label: "Documents", icon: FileCheck2 },
  { href: "/cards", label: "ID & Visiting Card", icon: IdCard },
  { href: "/attendance", label: "Attendance", icon: Fingerprint },
  { href: "/leave", label: "Leave", icon: CalendarCheck },
  { href: "/holidays", label: "Holidays", icon: CalendarDays },
  { href: "/organization", label: "Organization Chart", icon: GitFork },
  { href: "/payroll", label: "Payroll", icon: BadgeIndianRupee },
  { href: "/compliance", label: "Compliance", icon: Landmark },
  { href: "/expenses", label: "Expense Payout", icon: ReceiptText },
  { href: "/insurance", label: "Insurance Management", icon: HeartPulse },
  { href: "/support", label: "Support", icon: CircleHelp },
  { href: "/notifications", label: "Notifications", icon: Megaphone },
  { href: "/social", label: "SkyNexus", icon: MessageSquareText },
  { href: "/rewards", label: "Rewards", icon: Trophy },
  { href: "/reports", label: "Reports", icon: FileText },
  { href: "/security", label: "Security", icon: ShieldCheck },
  { href: "/settings", label: "Settings", icon: Settings },
];
